dist: xenial
language: python
python:
  - 3.6
  - 3.7
notifications:
  email:
    - nick.hand@phila.gov
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.conda"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - "./miniconda.sh -b -p $HOME/miniconda"
  - export PATH=$HOME/miniconda/bin:$PATH
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION
  - conda info
  - while read requirement; do conda install --yes $requirement || pip install $requirement;
    done < requirements.txt
  - pip install .[dev]
script:
  - py.test . --cov phlcensus
after_success:
  - coveralls
deploy:
  provider: pypi
  distributions: sdist
  user: __token__
  password:
    secure: NOa5zUVNMmDUuVrl6eWaSlpa3Fev4bikQVOc4qjBjqhyTzwLxfS3zpTTM7swty/gyLjfQwXCCK1y2N1LbveD938v7DdlEH70a5bfGHgeI9Vwdql7z1OmeeBbZwiAVI0rFbeT3eQJP6X4yf8OzC5MoB5w5lXxj/ksW+8qW/GOcpsFCkcv74zkdkuhlWBPbgGSPmvnf3R+BJNKbmDE8WFdzjmVZqGq558vUmPx1rk6l9R3r8HTsgKNaUOttq2Yp4NMM8Pr84WBsU05I2AO/6YsAjaDutKhruSTH04qKPrkdd+QYISPeFTGZ6X4i9ad/j0kmlaWjWdHWz6JlM/5JqsSOeHxIpufj+CDOVEx7x2SkpaEDRg7H794YGtoWZzieihSQOxYjVstoflbH7DyDCDwAXlBd9OCGnJfgAY3iU48pLW0RDTeJe9LvPdZBhbRyYD2xL0fxCkP6O6s6puVHekv7XUZyJ69HNWm47DkT7xZBiZtJnL5cKxtg6OdQhkHzEOX2oeGCvI1CMFfMkyy5VtVOqcD2xfX1ML7Ac/XH9AITxmhqy9gA9Z4LHf50eoR7H5mEsYTzGKIA90h4o/4nv2AAZlNU3e+/q5NTd/pMzL+lLX9MdhBnnWSZUH62wno45/JCx/Obo41sQAT10W5vFPqiOAVod32Kz+VHxLBU/HKqQA=
  skip_existing: true
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.7"
